---
- hosts: localhost
  gather_facts: False 
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks:

     - name: Prepare localhost for the deployment
       include_role:
         name: prepare-localhost

- name: Revert and power-on vms
  hosts: localhost
  gather_facts: False 
  become: yes
  become_user: root
  become_method: sudo

  vars:
    ansible_env_yaml: "/tmp/ansible-revert-yaml.yaml"

  pre_tasks:

     - name: Clean ansible yaml file
       shell: echo ''> {{ ansible_env_yaml }}

     - name: include vars file
       include_vars: "{{ ansible_env_yaml }}"
       register: env_vars

     - name: Display all variables/facts from the vsphere guest - vcenters
       debug:
         var: env_vars.ansible_facts.config[0].env_vcenters
       register: vcenters
       when: env_vars.ansible_facts.config[0].env_vcenters is defined

     - name: Display all variables/facts from the vsphere guest - hosts 
       debug:
         var: env_vars.ansible_facts.config[0].env_hosts
       register: hosts 
       when: env_vars.ansible_facts.config[0].env_hosts is defined

     - name: Display all variables/facts from the vsphere guest - k8s masters 
       debug:
         var: env_vars.ansible_facts.config[0].env_k8s_masters
       register: k8s_masters 
       when: env_vars.ansible_facts.config[0].env_k8s_masters is defined

     - name: Display vcenters hosts and k8s masters
       debug:
         var: "{{ item }}"
       with_items:
       - vcenters 
       - hosts 
       - k8s_masters 

     - name: Display k8s master 
       debug:
         var: k8s_masters

     - include_role:
         name: revert-role-vcenters 
       when: vcenters is not skipped and vcenters is not failed 

     - name: Revert k8s masters
       include_role: 
         name: revert-role-hosts
       when: hosts is not skipped and hosts is not failed

     - name: Revert k8s-masters 
       include_role: 
         name: revert-role-k8s-masters
       when: k8s_masters is not skipped and k8s_masters is not failed

