---
- name: Revert and power-on vms
  hosts: localhost
  gather_facts: False 
  become: yes
  become_user: root
  become_method: sudo

  pre_tasks:

     - name: include vars file
       include_vars: "{{ env_yaml }}"
       register: env_vars

     - name: Prepare localhost for the deployment
       include_role:
         name: prepare-localhost

     - name: Display all variables/facts from the vsphere guest - hosts 
       debug:
         var: env_vars.ansible_facts.config[0].env_hosts
       register: hosts 
       when: env_vars.ansible_facts.config[0].env_hosts is defined

     - name: Display vcenters hosts and k8s masters
       debug:
         var: "{{ item }}"
       with_items:
       - hosts 

     - name: Revert hosts 
       include_role: 
         name: revert-role-hosts
       when: hosts is not skipped and hosts is not failed
