---
    - name: include vars file 
      include_vars: "{{ ansible_env_yaml }}"

    - name: Gather facts from a vm located in vcenter 
      vmware_guest_facts:
        hostname: "{{ vcenter }}"
        username: "{{ vcuser }}" 
        password: "{{vcpass}}"
        name: "{{ item.1.ip }}"
        validate_certs: no
        datacenter: "{{ DC }}"
      delegate_to: localhost
      register: vm_facts
      when: item is defined and item.1.revert_vm.find("true") != -1
      with_subelements:
        - "{{ config }}"
        - env_hosts 

    - name: Display all variables/facts from the vsphere guest
      debug:
        var: vm_facts
      when: item.1.revert_vm.find("true") != -1
      with_subelements:
        - "{{ config }}"
        - env_hosts 

    - name: Display hw_folder of all variables/facts from the vsphere guest 
      debug:
        var: vm_facts.results[0].instance.hw_folder
      when: item.1.revert_vm.find("true") != -1
      with_subelements:
        - "{{ config }}"
        - env_hosts 

    - name: Revert Snapshot  
      vmware_guest_snapshot:
        hostname: "{{ vcenter }}"
        username: "{{ vcuser }}"
        password: "{{ vcpass }}"
        validate_certs: no
        datacenter: "{{ DC }}"
        folder: "{{ vm_facts.results[0].instance.hw_folder }}"
        name: "{{ item.1.ip }}" 
        state: revert 
        snapshot_name: "{{ snapshot }}"
      delegate_to: localhost
      register: snap
      when: item.1.revert_vm.find("true") != -1
      with_subelements:
        - "{{ config }}"
        - env_hosts 

    - name: Power-On VMs  
      vmware_guest:
        hostname: "{{ vcenter }}" 
        username: "{{ vcuser }}" 
        password: "{{ vcpass }}"
        validate_certs: no
        datacenter: "{{ DC }}"
        folder: "{{ vm_facts.results[0].instance.hw_folder }}"
        name: "{{ item.1.ip }}" 
        state: poweredon
      delegate_to: localhost
      register: power 
      when: item.1.revert_vm.find("true") != -1
      with_subelements:
        - "{{ config }}"
        - env_hosts 
